### PR TITLE
added youtube thumbnails

### LINKED ISSUE #24: Pull thumbnails from youtube for transcripts from btctranscript
"The thumbnail url can be determined in the front-end directly... https://i3.ytimg.com/vi/[YOUTUBE_ID]/maxresdefault.jpg"

From @aureleoules

Let's pull those and display them online for the search results that have a YouTube media field.

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
closes #24

### CODE REVIEW

**Comment by adamjonas** [comment]
Great. Let's overlay a rounded play button and make it linkable to the video itself.

Screen Shot 2023-01-23 at 3 30 00 PM

**Comment by Emmanuel-Develops** [comment]
> Great. Let's overlay a rounded play button and make it linkable to the video itself.
> 
> Screen Shot 2023-01-23 at 3 30 00 PM

I thought as much. Yeah, we can embed the youtube video, the link to the thumbnail image threw me off.

https://github.com/bitcoinsearch/bitcoinsearch-frontend/issues/24#issuecomment-1400739565

**Comment by Emmanuel-Develops** [comment]
Done. I set it to open in a new tab as well

**Comment by adamjonas** [comment]
The results are getting cut off on mobile. Here is the branch:

image

And here is the master branch:


image

**Pull request merged**
