### PR TITLE
feat: results container component and grouping of similar results in …

### LINKED ISSUE #28: Mailing list results repetition
The repetition of the mailing list makes the results noisey. 

Let's only show the original post and show just the titles of the thread urls below it. Sort of like the mailing list itself:
Screen Shot 2023-01-23 at 3 27 24 PM

However, when someone requests an author or other facet revert replies back to the expanded result (or at least the one first one). 

This can be filtered using the type field (they are labeled either "original_post" or "reply").

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
…specific domains

closes #28 

I noticed bitcoin_talk domain also has a lot of repetition in the results so I grouped it as well

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
This PR covers the grouping, If the implementation is sufficient then we discuss the implementation for the results when some facets are selected

**Comment by adamjonas** [comment]
Is this branch rebased on master? It seems like the default is 20 again.

**Comment by adamjonas** [comment]
I really like the choices you made here. Good job! I will work on cleaning this up on the backend to make the results even more coherent.

It feels weird that prior mailing list posts are in the pull-down as a result of boosting certain authors and keywords found in the body. But I'm happy with this as it was the last thing that was really bothering me before sharing this more widely.

**Comment by Emmanuel-Develops** [comment]
> I really like the choices you made here. Good job! I will work on cleaning this up on the backend to make the results even more coherent.
> 
> It feels weird that prior mailing list posts are in the pull-down as a result of boosting certain authors and keywords found in the body. But I'm happy with this as it was the last thing that was really bothering me before sharing this more widely.

Awesome. Glad to hear that ✨

**Pull request merged**
