### PR TITLE
Add tags to search results

### LINKED ISSUE #20: Add tags to results
Add tags to the pills at the bottom of each result.

Not sure on the colors here. Maybe it makes sense to differentiate.

A click on a pill should highlight that facet both in the sidebar and in the results. Clicking it again should remove the filter.

Screen Shot 2023-01-16 at 8 08 39 PM

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
closes #20

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
I changed the color of the sub link from green to a darker grey shade, given that its not clickable it probably shouldn't have a high visual hierarchy.

**Comment by Emmanuel-Develops** [comment]
Also the tags in the results shows tags and authors. Wasn't sure whether to remove authors or not? I wrote it as a config from engine.json. So it's really straightforward to remove authors if we don't want them. I'd like to hear your thoughts on this

**Comment by adamjonas** [comment]
> I changed the color of the sub link from green to a darker grey shade, given that its not clickable it probably shouldn't have a high visual hierarchy.

As mentioned in https://github.com/bitcoinsearch/bitcoinsearch-frontend/pull/21#issuecomment-1397834001, I think it makes sense to only change one feature at a time. Clickable tags and this styling don't seem coupled to me.

**Comment by adamjonas** [comment]
I don't like the labels. Can we make the unselected bubbles different colors to indicate a differentiation? Maybe this is a worth a user test.

**Comment by adamjonas** [comment]
I love how the bubbles click though. It's fun to make the different combinations. This will be a good feature addition.

**Comment by Emmanuel-Develops** [comment]
> > I changed the color of the sub link from green to a darker grey shade, given that its not clickable it probably shouldn't have a high visual hierarchy.
> 
> As mentioned in [#21 (comment)](https://github.com/bitcoinsearch/bitcoinsearch-frontend/pull/21#issuecomment-1397834001), I think it makes sense to only change one feature at a time. Clickable tags and this styling don't seem coupled to me.

You're right. It didn't occur to me at the time but yes they aren't coupled.

**Comment by Emmanuel-Develops** [comment]
> I don't like the labels. Can we make the unselected bubbles different colors to indicate a differentiation? Maybe this is a worth a user test.

Screenshot 2023-01-21 at 6 23 20 PM

I can try out different colors and shapes maybe an icon too for the selected bubbles, but generally grey is neutral and I think that works for not selected.

**Comment by adamjonas** [comment]
Let's do a v1 without the labels and keeping the grey background.

**Comment by adamjonas** [comment]
I'd like to restore the url green color and make the url linkable.

**Comment by Emmanuel-Develops** [comment]
> Details

Alright. To clarify, without the labels "authors" and "tags" correct?

Okay, I'll restore the green. The URL (in green) was never a link, you can still copy the link by right clicking or highlighting.
hovering or clicking any part of the link (title or the full URL underneath) opens the link.
This behaviour was inspired by google search (in hindsight should have been a different PR/Issue)   

Making the URL underneath clickable means both text do the same action. Is this behaviour alright?

**Comment by adamjonas** [comment]
Yes. That sounds good.

**Comment by Emmanuel-Develops** [comment]
Done

**Pull request merged**
